node {

    withMaven(maven:'maven') {

        stage('Checkout') {
            git url: 'https://github.com/MadeInChina/sample-spring-microservices.git', credentialsId: 'github-slam', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('discovery-service') {
                //def app = docker.build "slamhan/discovery-service:${env.version}-${env.BUILD_NUMBER}"
                def app = docker.build "slamhan/discovery-service:latest
                // requested access to the resource is denied app.push()
            }
        }

        stage ('Upgrade') {
            dir ('discovery-service') {
            sh 'rancher-compose docker-compose.yml --url http://192.168.2.34:8888/v2-beta/projects/1a5  --access-key 49351B9F554343DA1149 --secret-key zq5ucfRQGDGhHaV7Cr2dCsptCenE8gvyuSQiwwe8 up --upgrade --confirm-upgrade'
            //docker.image("slamhan/discovery-service:${env.version}-${env.BUILD_NUMBER}").run('-p 8761:8761 -h discovery --name discovery')
            }
        }

        stage ('Final') {
            build job: 'account-service-pipeline', wait: false
        }      

    }

}